// Code generated by "stringer -type=PanelType -output=defs.go ioloop.go"; DO NOT EDIT.

package concord

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Concord-20]
}

const _PanelType_name = "Concord"

var _PanelType_index = [...]uint8{0, 7}

func (i PanelType) String() string {
	i -= 20
	if i >= PanelType(len(_PanelType_index)-1) {
		return "PanelType(" + strconv.FormatInt(int64(i+20), 10) + ")"
	}
	return _PanelType_name[_PanelType_index[i]:_PanelType_index[i+1]]
}
